export const FETCH_SUCCESS = "KEYWORD/FETCH_SUCCESS";
export const FETCH_PEDING = "KEYWORD/FETCH_PEDING";
export const FETCH_FAIL = "KEYWORD/FETCH_FAIL";
export const CHANGE_KERSEARCH = "KEYWORD/CHANGE_KERSEARCH";