export const FETCH_SUCCESS = "CART/FETCH_SUCCESS";
export const FETCH_PEDING = "CART/FETCH_PEDING";
export const FETCH_FAIL = "CART/FETCH_FAIL";
export const CHOSE_CART_ITEM = "CART/CHOSE_CART_ITEM";
export const UPDATE_ALL_CART_ITEM = "CART/UPDATE_ALL_CART_ITEM";
export const UPDATE_ALL_CART_ITEM_IN_SHOP = "CART/UPDATE_ALL_CART_ITEM_IN_SHOP";
export const ATTACH_MESSAGE = "CART/ATTACH_MESSAGE";